
pipeline { 
	  agent any
	  
    	tools {
			 gradle "GRADLE" 
		 }
		 
		stages {
			stage ('Unit Tests') {
				steps {
					dir('arabic-to-roman'){
						sh 'gradle test --tests *UnitTest*'
					}
				}
			}
		
			stage('Static Code Analysis') {
				steps {
					withSonarQubeEnv('sonarqube'){						
						dir('arabic-to-roman'){
							sh 'gradle --info sonarqube -x test'
						} 	
					}
				}
			}
			
			stage('Quality Gate') {
            	steps {
                    script {
                        timeout(time: 10, unit: 'MINUTES') {
                            def qg = waitForQualityGate()
                            if (qg.status != 'OK') {
                                error "Pipeline aborted due to quality gate failure: ${qg.status}"
                            }
                        }
                    	
                	}
            	}
        	}
        	
			stage ('Build code') {
				steps {
					dir('arabic-to-roman'){
						sh 'gradle build -x test'
					} 
				}
			}
			
			stage ('Create Docker Images') {
		  		steps {
		  		dir('arabic-to-roman'){
					sh 'docker build -f Dockerfile -t arabicToRoman.jar .'
				}
				}
		 	}
		}
	}